sonar.projectKey=frontend-service
sonar.projectName=Frontend Service
sonar.sources=frontend
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/coverage/**
sonar.coverage.exclusions=**/*,**/*.js,**/*.jsx,frontend/**/*
sonar.cpd.exclusions=**/*,**/*.js,**/*.jsx,frontend/**/*